//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalibreImport.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CalibreImport.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to also log for debugging.
        /// </summary>
        internal static string AlsoDebugLog {
            get {
                return ResourceManager.GetString("AlsoDebugLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following Calibre-related processes are running and will be terminated:.
        /// </summary>
        internal static string CalibreProcessesRunning {
            get {
                return ResourceManager.GetString("CalibreProcessesRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to calibre.exe is running. Would you like to terminate it?.
        /// </summary>
        internal static string CalibreRunning {
            get {
                return ResourceManager.GetString("CalibreRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibre process running.
        /// </summary>
        internal static string CalibreRunning2 {
            get {
                return ResourceManager.GetString("CalibreRunning2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to proceed?.
        /// </summary>
        internal static string DoYouWantToProceed {
            get {
                return ResourceManager.GetString("DoYouWantToProceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What to do with duplicate books:.
        /// </summary>
        internal static string DuplicatesWhat {
            get {
                return ResourceManager.GetString("DuplicatesWhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error launching Calibre.
        /// </summary>
        internal static string ErrorLaunching {
            get {
                return ResourceManager.GetString("ErrorLaunching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check libraries to hide them from submenu.
        /// </summary>
        internal static string HideLibraries {
            get {
                return ResourceManager.GetString("HideLibraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string ImportBtn {
            get {
                return ResourceManager.GetString("ImportBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to import files. Check the log for details..
        /// </summary>
        internal static string ImportFailure {
            get {
                return ResourceManager.GetString("ImportFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibre Import.
        /// </summary>
        internal static string ImportForm {
            get {
                return ResourceManager.GetString("ImportForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing....
        /// </summary>
        internal static string Importing {
            get {
                return ResourceManager.GetString("Importing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ImportSubmenuIcon {
            get {
                object obj = ResourceManager.GetObject("ImportSubmenuIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files imported successfully. Would you like to launch Calibre?.
        /// </summary>
        internal static string ImportSuccess {
            get {
                return ResourceManager.GetString("ImportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid selection of files.
        /// </summary>
        internal static string InvalidFiles {
            get {
                return ResourceManager.GetString("InvalidFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid selection of files.
        /// </summary>
        internal static string InvalidSelection {
            get {
                return ResourceManager.GetString("InvalidSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto close Calibre before importing.
        /// </summary>
        internal static string KillCalibre {
            get {
                return ResourceManager.GetString("KillCalibre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log eBooks being imported.
        /// </summary>
        internal static string LogEbooks {
            get {
                return ResourceManager.GetString("LogEbooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon MainAppIcon {
            get {
                object obj = ResourceManager.GetObject("MainAppIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import To Calibre.
        /// </summary>
        internal static string MenuText {
            get {
                return ResourceManager.GetString("MenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibre Import.
        /// </summary>
        internal static string NameApp {
            get {
                return ResourceManager.GetString("NameApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CalibreImport.
        /// </summary>
        internal static string NameAppShort {
            get {
                return ResourceManager.GetString("NameAppShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import to Calibre Settings:.
        /// </summary>
        internal static string NameSettingsForm {
            get {
                return ResourceManager.GetString("NameSettingsForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Calibre libraries found..
        /// </summary>
        internal static string NoLibraries {
            get {
                return ResourceManager.GetString("NoLibraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to the Calibre folder:.
        /// </summary>
        internal static string PathToCalibre {
            get {
                return ResourceManager.GetString("PathToCalibre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a library..
        /// </summary>
        internal static string PleaseSelectLibrary {
            get {
                return ResourceManager.GetString("PleaseSelectLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration failed.
        /// </summary>
        internal static string RegistrationFailed {
            get {
                return ResourceManager.GetString("RegistrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select language:.
        /// </summary>
        internal static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Calibre library.
        /// </summary>
        internal static string SelectLibrary {
            get {
                return ResourceManager.GetString("SelectLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the context menu entry:.
        /// </summary>
        internal static string SetEntryName {
            get {
                return ResourceManager.GetString("SetEntryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings saved successfully..
        /// </summary>
        internal static string SettingsSaved {
            get {
                return ResourceManager.GetString("SettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Submenu rather than a dialog.
        /// </summary>
        internal static string UseSubmenu {
            get {
                return ResourceManager.GetString("UseSubmenu", resourceCulture);
            }
        }
    }
}
